on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-name:
        - rentx_test
        database-password:
        - ignite
        database-user:
        - docker
        database-host:
        - 127.0.0.1
        database-port:
        - 5432
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: rentx_test        
          POSTGRES_PASSWORD: ignite
          POSTGRES_USER: docker
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Get main
        run: git fetch origin main
      - name: Install dependencies
        run: npm install
      - name: Install Jest globally
        run: sudo npm install -g jest
      - name: Run Tests
        env:
          DATABASE_NAME_TEST: ${{ matrix.database-name }}
          DATABASE_USER: ${{ matrix.database-user }}
          DATABASE_PASSWORD: ${{ matrix.database-password }}
          DATABASE_HOST: ${{ matrix.database-host }}
          DATABASE_PORT: ${{ matrix.database-port }}
          POSTGRES_DB: ${{ matrix.database-name }}
        run: npm run test:sonar
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
